export const PROVIDER = {
  TENANT_CONNECTION: 'TENANT_CONNECTION',
  COMPANY_MODEL: 'COMPANY_MODEL',
  TENANT_MODEL: 'TENANT_MODEL',
  PLAN_MODEL: 'PLAN_MODEL',
  COMPANY_SCHEDULE_MODEL: 'COMPANY_SCHEDULE_MODEL',
};
